Simple post story / passes simple_post acceptance test
ikarabulut/HttpServer pull request #23
Opened 2022-07-06 18:01 UTC by ikarabulut

This PR covers the additional features added to get the `simple_post` acceptance test passing.

Features added:

- `PostRequestHandler` this `RequestHandler` object currently implements `processResponse()` and hardcodes the body of the response to be the body of the request that came in.
	- This uses the new `parseBody()` method within `RequestParser` which returns a `String` object representing the body of the request
- `PostResponse` this `Response` object implements the abstract `Response` methods to generate the headers, and generate a string object representing the response. 
- These added features are similar in implementation to the other `RequestHandler` and `Response` objects within the program.

Potential improvements to consider:

- Allowing the Headers to be dynamically generated. I set up `generateHeaders()` to be a bit more flexible in potentially adding a new object whos purpose is to generate headers. so instead of `generateHeaders` returning a `Map` it can return a `Header` object that can have its data accessed similar to `RequestParser` 
- Implementing a feature to dynamically grab the body response for a `Post` request. Instead of hardcoding the body within the `processResponse` method in `PostRequestHandler` . I'm anticipating that this will be addressed when later features are implemented.

2022-07-07 17:57 UTC, ikarabulut commented on app/src/main/java/ikarabulut/http/handlers/PostRequestHandler.java
> +    public PostRequestHandler(RequestParser parsedRequest) {
I relied on Intellij Refactoring here and didn't double check to make sure everything was properly changed. Ill go back in and make the update to the name

2022-07-07 18:00 UTC, ikarabulut commented on app/src/test/java/ikarabulut/http/handlers/PostRequestHandlerTest.java
> +    @DisplayName("PostRequestHandler should echo back the body of the request by calling parseBody from the composed RequestParser")
copy paste error. updated

2022-07-07 18:01 UTC, ikarabulut commented on app/src/test/java/ikarabulut/http/parser/RequestParserTest.java
> +    @DisplayName("A Request without a body should return a null body object")
True. Updated

2022-07-07 18:03 UTC, ikarabulut commented on app/src/test/java/ikarabulut/http/response/PostResponseTest.java
> +    @DisplayName("PostResponse should be able to generate headers with at minimum the date")
I am planning on expanding the headers to be more dynamic so I didn't want to put a constraint on that with my tests this early on.

2022-07-07 18:06 UTC, jramnani commented on app/src/main/java/ikarabulut/http/parser/RequestParser.java
> +        return null;
Why return null instead of an empty String?

2022-07-07 18:17 UTC, riccjohn requested changes
The `PostRequestHandlerTest` has two tests that are doing the same thing as far as I can tell.

2022-07-07 18:17 UTC, riccjohn commented on app/src/test/java/ikarabulut/http/handlers/PostRequestHandlerTest.java
> +    @DisplayName("PostRequestHandler should echo back the body of the request by calling parseBody from the composed RequestParser")
Blocker: The description changed, but the contents of the test are still the same.

2022-07-07 18:36 UTC, jramnani approved these changes
Once John's concerns are taken care of I'm good. 👍

2022-07-07 20:02 UTC, ikarabulut commented on app/src/test/java/ikarabulut/http/handlers/PostRequestHandlerTest.java
> +    @DisplayName("PostRequestHandler should echo back the body of the request by calling parseBody from the composed RequestParser")
The first test is verifying that `parseInitialLine()` is called and the second test is verifying that `parseBody()` is called? The test is for the same method call but two different behaviors

2022-07-07 20:12 UTC, ikarabulut commented on app/src/main/java/ikarabulut/http/parser/RequestParser.java
> +        return null;
Building off of the [Slack Convo](https://8thlight.slack.com/archives/C033HEKJ2LC/p1657218431622889) I need to get better at returning base cases of these sorts of types. I updated it and will be more conscious of it moving forward

2022-07-07 21:52 UTC, riccjohn commented on app/src/test/java/ikarabulut/http/handlers/PostRequestHandlerTest.java
> +    @DisplayName("PostRequestHandler should echo back the body of the request by calling parseBody from the composed RequestParser")
Sorry, the commit didn't update for me.

Ok, I see the change here. I think that's fine, but I don't think it's testing what the test description says. This is just testing that the body gets parsed. If you want to test what the descriptions says, you'll need to assert that a new PostResponse is created with the same body. I'd also word it a bit differently, because at this class level, we don't know it'll get echoed back to the user. All we know is "`processResponse returns a new `PostResponse` with the given request's body."

2022-07-08 14:58 UTC, ikarabulut commented on app/src/test/java/ikarabulut/http/handlers/PostRequestHandlerTest.java
> +    @DisplayName("PostRequestHandler should echo back the body of the request by calling parseBody from the composed RequestParser")
Good point. I did get too descriptive with the test name. Im realized that I tend to do that when Im writing my tests. I look forward to what the full integration should do when I should really be focusing on what that specific unit is doing when called. 

My goal with this test is to ensure that when processResponse is called parseBody is also called within. The next part is to make sure that it is passed as a param to `PostResponse` but it is difficult to test constructors unless I create a wrapper class and I do not think that is necessary for this unit.

The downside to this approach would be that how would a future developer know to pass that specific body into `PostResponse` and then another downside I just thought of was now `PostRequestHandler` is constrained by this test because what if a `POST` request comes in that does not want its body echoed back to it. In which case I could use this class as a subclass of a `PostRequestHandler` superclass. Like call this one `EchoPostRequestHandler` so the client knows that if you use this object for a `Post` request then it will echo the body back to the client. 

I think the latter approach would be a better way to go moving forward if that requirement does come up.

2022-07-08 15:09 UTC, ikarabulut commented on app/src/test/java/ikarabulut/http/handlers/PostRequestHandlerTest.java
> +    @DisplayName("PostRequestHandler should echo back the body of the request by calling parseBody from the composed RequestParser")
Also whats interesting is jacoco is saying 100% of the `processResponse` method is covered
<img width="610" alt="Screen Shot 2022-07-08 at 10 08 32 AM" src="https://user-images.githubusercontent.com/61036790/178020085-378c9f29-d43a-446c-92be-39c6f8f87a70.png">

2022-07-08 15:18 UTC, riccjohn commented on app/src/test/java/ikarabulut/http/handlers/PostRequestHandlerTest.java
> +    @DisplayName("PostRequestHandler should echo back the body of the request by calling parseBody from the composed RequestParser")
I think jacoco is telling you it's fully covered because the logic that I think is technically untested is in the `return` statement, and it's saying "well, your test _does_ cause me to return something, so this is covered". I think there's a few ways to test this that don't involve testing a constructor. Essentially, the test that I think is missing is "when I call `processResponse` I get this thing back". Right now, you're testing what happens inside the method, but not what the method returns. I know the types already ensure that we get a `Response` back, but maybe you could write an assertion that says the body in the returned Response is the same as the body in the rawRequest? Just a suggestion though.

2022-07-08 15:22 UTC, riccjohn approved these changes

2022-07-08 15:28 UTC, ikarabulut commented on app/src/test/java/ikarabulut/http/handlers/PostRequestHandlerTest.java
> +    @DisplayName("PostRequestHandler should echo back the body of the request by calling parseBody from the composed RequestParser")
I went down a [similar rabbit hole](https://github.com/ikarabulut/HttpServer/pull/4/files/8dd3bb8eaa2baa604a44d73b111d6991e735921f#r885745512) with the Echo Server on this same topic. Idk if it is a java thing or i haven't found the right solution. I understand what you are saying, I just haven't been able to figure out how to properly test that

2022-07-08 15:45 UTC, ikarabulut commented
Merging to main

2022-07-08 15:46 UTC, merged

2022-07-08 16:35 UTC, riccjohn commented on app/src/test/java/ikarabulut/http/handlers/PostRequestHandlerTest.java
> +    @DisplayName("PostRequestHandler should echo back the body of the request by calling parseBody from the composed RequestParser")
I don't think you'd need to spy on the constructor here though.