Simple_head story
ikarabulut/HttpServer pull request #9
Opened 2022-06-09 19:42 UTC by ikarabulut

PR based on [Simple_head feature](https://trello.com/c/PT3GipuM)

This PR passes the acceptance tests for
01_getting_started -> simple_head.feature
`Scenario: Executing a HEAD request to /simple_get`
` Scenario: HEAD does not include body`

Major changes include:
- `EchoServer` class has been updated to `Server` in this updated class, it now takes in a `ServerWrapper` class which can create a `ServerSocket` and can have a `ServerSocket.accept()` creating a `Socket`. 
- The larger `App` method has been moved into `Server` which is now `start()` which creates the `ServerSocket` and then generates the `ThreadPool` and starts the `while` loop that runs while the `ServerSocket` is open.
- The `ClientHandler` has stayed mostly the same, which is executed within the `Server` `start()` method. 
- When the `Socket` is generated and receives a request, the request is passed to the **new** `RequestParser` which can parse the initial line and the headers for now.
- The parsed information is passed to the **new** `Router` object, which takes the method and will execute the proper `RequestRunner`which reads from a local `.txt` file that stores all of the valid paths for each method. 
- The runner will then process the response by passing the information to its proper `ResponseHandler` which returns the string version of the response for a HEAD request.

2022-06-09 21:29 UTC, riccjohn requested changes
I haven't had time to look through all this, so I'm just submitting this partial review for the moment, and then I'll look through the rest.

2022-06-09 21:29 UTC, riccjohn commented on app/src/test/java/com/ikarabulut/requests/HeadRequestRunnerTest.java
> +        HashMap<String, String> initialLine = new HashMap<>();
Is it possible to initialize a new HashMap with given values instead of adding them one by one? I'm not sure if Java allows this, but I'm thinking maybe you could do something like this.

```
HashMap<String, String> initialLine = new HashMap<>({
  httpMethod,
  httpPath,
  httpVersion
});
```

If you can't, then I'd move this sort of thing to a help method so you don't have to spend so many lines doing test setup. This would also allow you to use the same method between all your specs in this file, which would make the specs easier to read.

2022-06-09 21:29 UTC, riccjohn commented on app/src/test/java/com/ikarabulut/requests/HeadRequestRunnerTest.java
> +        HeadRequestRunner headRequestRunner = new HeadRequestRunner(initialLine);
Try to keep each test split up into arrange, act, and assert sections. That might be as simple as moving the `new HedReaquestRunner` below the `expectedGetValidPaths` call and making sure you have 3 clear sections.

```
setup
setup
setup

action
action
action

assertion
```

2022-06-09 21:29 UTC, riccjohn commented on app/src/test/java/com/ikarabulut/requests/HeadRequestRunnerTest.java
> +        expectedGetValidPaths();
This seems odd to me. You're essentially duplicating part of your production code and then putting it in your specs and saying "calling the production code should match the call to this method", but they're the same method. So if you have a bug in your production code, you'd have the same bug here, and the test would pass. Also, if you had to change your prod code, you'd have to change this too.

Instead, I'd just manually write in what your expected values should be. Don't _actually_ parse the .txt file in the specs. I think the name of `expectedGetValidPaths` is a little confusing too. I think what you're actually trying to return is the `expectedPaths`, but again, it's the same logic you're running the tests against.

2022-06-11 01:40 UTC, jramnani reviewed
In decent shape, but still some room for improvement.  Left some notes we can talk over later.

2022-06-11 01:40 UTC, jramnani commented on app/src/test/java/com/ikarabulut/parser/RequestParserTest.java
> +        expectedHeaders.put("Content-Type:", "text/plain");
The colon is not meant to be part of the header name, it is the separator between the header name and value. That looks like a parsing error.

For example: the HTTP header is `Content-Type`, not `Content-Type:`.

https://www.rfc-editor.org/rfc/rfc2616#section-14.17

2022-06-11 01:40 UTC, jramnani commented on app/src/test/java/com/ikarabulut/requests/HeadRequestRunnerTest.java
> +    @DisplayName("When a passed path is not allowed then isValidPath should return false")
We can ditch the word, "passed", since it is superfluous.  Function arguments are assumed to be passed to the function.

For example, "When a path is not allowed...". It makes the tests read a little tighter and more clear.

2022-06-13 20:34 UTC, ikarabulut commented on app/src/test/java/com/ikarabulut/requests/HeadRequestRunnerTest.java
> +        HashMap<String, String> initialLine = new HashMap<>();
I updated the variable to be an in-line string. I get what you mean about its readability, I was trying to make it more explicit but with the setup it is easier to read and understand in-line

2022-06-13 20:40 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/App.java
> +        ServerWrapper serverWrapper = new ServerWrapper();
My plan with this was to turn the `Server` class into the class that holds the logic for the program. The `ServerWrapper` creates the `ServerSocket` and `ClientSocket`. So a `Server` object takes in a `ServerWrapper` object to be used to generate client and server sockets as needed.

To be fully transparent, this was also a case of following the crowd. This class has been thrown around on pretty much every other apprentices implementation so I went with it as well.

2022-06-13 21:03 UTC, ikarabulut commented on app/src/test/java/com/ikarabulut/requests/HeadRequestRunnerTest.java
> +    private void expectedGetValidPaths() {
Tried to get too fancy here, my thought was that as paths get added it is easier to update a file rather than the production code. I talked to John about this. Ill be going back to just have the class configured with a list of allowed paths

2022-06-13 21:06 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/server/Server.java
> +                threadPool.execute(new ClientHandler(clientSocket,serverIO));
Ugh 😫

2022-06-13 21:08 UTC, ikarabulut commented on app/src/test/java/com/ikarabulut/requests/HeadRequestRunnerTest.java
> +        expectedGetValidPaths();
Ill be updating this to not take in a file. It adds unnecessary complexity early on

2022-06-13 21:40 UTC, ikarabulut commented on app/src/test/java/com/ikarabulut/requests/HeadRequestRunnerTest.java
> +        HeadRequestRunner headRequestRunner = new HeadRequestRunner(initialLine);
I try to be conscious of this but always seem to let it slip

2022-06-13 21:51 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/requests/HeadRequestRunner.java
> +            ex.printStackTrace();
If the file can't be find the program wouldn't be able to continue successfully. Idk why Im stuck in this pattern of only catching exceptions to print out the errors. 

I did remove this feature to get the accepted paths from a file. But this is a good topic to cover. Ill be more conscious of this.

When it comes to unrecoverable exceptions, is it best to just have a `system.exit()`? Im sure its case by case but for something like this, the program wouldn't be able to function if the file is corrupted so exiting would be the best route in my mind

2022-06-13 22:26 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/response/StatusCode.java
> +    public String getStatusCode() {
Updated `getStatusCode()` to `getStatusNumber()` in the enum

The caller now creates a `StatusCode` object that will return the name of the enum. in this case 'OK'
It then calls the enums updated `getStatusNumber()` method which returns a String which is the value of the enum.

2022-06-14 16:22 UTC, ikarabulut commented on app/src/test/java/com/ikarabulut/parser/RequestParserTest.java
> +        expectedHeaders.put("Content-Type:", "text/plain");
So this should be "Content-Type" + ":" ?

Im confused because in the HTTP Made Really Easy article they provide a [sample exchange](https://www.jmarshall.com/easy/http/#sample) where it shows "Content-Type:"

2022-06-14 16:46 UTC, ikarabulut commented on app/src/test/java/com/ikarabulut/parser/RequestParserTest.java
> +        expectedHeaders.put("Content-Type:", "text/plain");
Oh wait, I see my error now. This is testing the Hashmap that is created to store the headers. The colon should not be in the key. I made the proper adjustments.

2022-06-14 16:50 UTC, ikarabulut commented
@riccjohn @jramnani @claudiahalip I just pushed my changes based on the feedback provided.

2022-06-14 22:13 UTC, riccjohn commented
Still going through, but here's some WIP feedback. I'll keep going through tomorrow.

2022-06-14 22:14 UTC, riccjohn commented on app/src/main/java/com/ikarabulut/server/Server.java
> +    public void start() throws IOException {
After our convo at the daily sync today (6/14), I realized it _can_ throw. We talked about possibly delegating to two helper methods that can deal with catching errors from create client and server sockets.

2022-06-15 15:12 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/server/http/Router.java
> +        return null;
My original plan was to return `method_not_found` here but now that Im thinking about it, that might not be a good idea since it could be a server error that causes the method to not be parsed correctly. And I don't want the client thinking its an issue on their end if it is a server-side error. 

I also don't like how it returns a String, I need to think through how I want to handle this

2022-06-15 15:27 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/server/Server.java
> +        int corePoolSize = 5;
If I store them as env variables then I would have to share the `.idea/workspace.xml` file which includes other workspace settings that may mess with another persons workspace.

Is there a way to set up env variable locally in the production code? Im doing some research now as well.

2022-06-15 15:41 UTC, jramnani commented on app/src/main/java/com/ikarabulut/App.java
> +            System.err.print("Unable to connect server, please review stacktrace for more details");
When returning an error to a user, I recommend also setting the program's exit code to something non-zero. That signals to the user (via the shell) that the command did not complete successfully.

https://shapeshed.com/unix-exit-codes/
https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#exit-int-

e.g. `System.exit(1)`

2022-06-15 15:42 UTC, jramnani commented on app/src/main/java/com/ikarabulut/App.java
> +            System.err.print("Unable to connect server, please review stacktrace for more details");
This also makes it easier for shell scripts to interact with your program and be able to know if an error occurred.  Imagine, for example, if we were to create an init script for this program so it could be started automatically when a server boots up. Via `systemd` for example.

2022-06-15 15:51 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/server/Server.java
> +    public void start() throws IOException {
I extracted the `while (serverSocket.isBound())` loop into a private method which catches its own exception.

2022-06-15 18:30 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/App.java
> +            System.err.print("Unable to connect server, please review stacktrace for more details");
Thank you for the resources and explanation

2022-06-15 19:15 UTC, jramnani commented on app/src/main/java/com/ikarabulut/server/Server.java
> +        int corePoolSize = 5;
Environment variables could be documented in the project README letting users know how to run the program. There are also shell tools that help with this like [direnv](https://direnv.net/) and [dotenv](https://www.dotenv.org/).

2022-06-16 01:26 UTC, jramnani commented on app/src/main/java/com/ikarabulut/server/ServerFactory.java
> +public class ServerFactory {
Often we name Factories after the objects that they create. What kind of objects does this class create?

2022-06-16 01:30 UTC, jramnani commented on app/src/main/java/com/ikarabulut/server/http/Router.java
> +        return null;
We can change it later once we learn more about the problem being solved. Once we learn more a solution may present itself.

However, I do ask that if this method explicitly returns a `null`, then the caller must check for it and figure out what to do with it so the program is correct and does not accidentally handle corrupt data.

2022-06-16 01:31 UTC, jramnani commented on app/src/main/java/com/ikarabulut/server/http/Router.java
> +        return null;
Actually, it's taken us so long to review this, it's not a blocker.  Let's learn more about the next HTTP method we implement! :)

2022-06-16 02:12 UTC, jramnani commented on app/src/test/java/com/ikarabulut/parser/RequestParserTest.java
> +        System.setIn(in);
Something I forgot to ask last time: do we still need to set `System.in` here? Could line 22 take the InputStream created on line 20?

I'm just wondering if that layer of indirection is needed anymore.

2022-06-16 02:21 UTC, jramnani commented on app/src/test/java/com/ikarabulut/parser/RequestParserTest.java
> +        System.setIn(in);
Also, I don't think we're resetting STDIN after this test runs either.

2022-06-16 02:39 UTC, jramnani approved these changes
LGTM for now. Let's see what we learn when we work on the next story. Thanks for taking our feedback.

2022-06-16 15:47 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/server/Server.java
> +        int corePoolSize = 5;
direnv is cool! I added a `.env` file that stores the local variables and a `.envrc` file that holds a simple bash script that will load the `.env` files locally using `direnv allow`. Updated readme as well to reflect these changes

2022-06-16 16:08 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/server/Server.java
> +        int corePoolSize = 5;
Had an issue with the build but added the env variables to the workflow. All is good now

2022-06-16 16:25 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/server/http/Router.java
> +        return null;
Sounds good, this is something I do want to pay more attention to in my next story and try to come up with a better way to handle the methods.

2022-06-16 16:26 UTC, ikarabulut commented on app/src/main/java/com/ikarabulut/server/ServerFactory.java
> +public class ServerFactory {
I changed it to SocketFactory, as a temp fix. But I do want to look into the necessity of this class in my next story and refactor this a bit.

2022-06-16 17:34 UTC, merged